#!/bin/sh

rm -r build build2

set -e

# Run original bundler
lua src/init.lua src build --log-level=error -l parser -l ext -l table
# Check that the bundled bundler can bundle
lua build/init.lua src build2 --log-level=error -l parser -l ext -l table

# Check that the bundled bundler built by the bundled bundler runs within its own directory.
cd build2; lua init.lua --help > /dev/null

echo "ok"